#!/bin/sh
# The lipsia post installation maintainer script.
# This script is called during the dpkg installation procedure.
#
# For more infos see:
# http://www.debian.org/doc/debian-policy/ch-maintainerscripts.html

set -e

case "$1" in
  configure)
    # update the ld cache
    ldconfig;
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2    
    exit 1;
  ;; 
esac

exit 0;
