debian/tmp/usr/bin/vcheckdesign usr/bin
debian/tmp/usr/bin/vlcorr usr/bin
debian/tmp/usr/bin/vledit usr/bin
debian/tmp/usr/bin/vlserv usr/bin
debian/tmp/usr/bin/vlv usr/bin
debian/tmp/usr/bin/vlview usr/bin
debian/tmp/usr/bin/vqview usr/bin
debian/tmp/usr/bin/vsendserv usr/bin
debian/tmp/usr/bin/vsview usr/bin

debian/tmp/usr/lib/lipsia/libvlh.a usr/lib/lipsia
debian/tmp/usr/lib/lipsia/libvlh.so usr/lib/lipsia
debian/tmp/usr/lib/lipsia/libvlh.so.2.2.8 usr/lib/lipsia
