# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Preprocessing_Layouted.ui'
#
# Created: Mon Mar 12 14:32:32 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Fenster(object):
    def setupUi(self, Fenster):
        Fenster.setObjectName("Fenster")
        Fenster.resize(625, 744)
        self.verticalLayout = QtGui.QVBoxLayout(Fenster)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(Fenster)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_general = QtGui.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_general)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.l_input_files = QtGui.QLabel(self.tab_general)
        self.l_input_files.setObjectName("l_input_files")
        self.verticalLayout_5.addWidget(self.l_input_files)
        self.lw_input_files = QtGui.QListWidget(self.tab_general)
        self.lw_input_files.setObjectName("lw_input_files")
        self.verticalLayout_5.addWidget(self.lw_input_files)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b_add_image_file = QtGui.QPushButton(self.tab_general)
        self.b_add_image_file.setCheckable(False)
        self.b_add_image_file.setAutoRepeatDelay(300)
        self.b_add_image_file.setObjectName("b_add_image_file")
        self.horizontalLayout_4.addWidget(self.b_add_image_file)
        self.b_add_image_directory = QtGui.QPushButton(self.tab_general)
        self.b_add_image_directory.setAutoDefault(False)
        self.b_add_image_directory.setObjectName("b_add_image_directory")
        self.horizontalLayout_4.addWidget(self.b_add_image_directory)
        self.b_remove_file = QtGui.QPushButton(self.tab_general)
        self.b_remove_file.setObjectName("b_remove_file")
        self.horizontalLayout_4.addWidget(self.b_remove_file)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.l_preprocessing_steps = QtGui.QLabel(self.tab_general)
        self.l_preprocessing_steps.setMinimumSize(QtCore.QSize(0, 16))
        self.l_preprocessing_steps.setMaximumSize(QtCore.QSize(16777215, 16))
        self.l_preprocessing_steps.setObjectName("l_preprocessing_steps")
        self.verticalLayout_2.addWidget(self.l_preprocessing_steps)
        self.cb_fieldmap_correction = QtGui.QCheckBox(self.tab_general)
        self.cb_fieldmap_correction.setObjectName("cb_fieldmap_correction")
        self.verticalLayout_2.addWidget(self.cb_fieldmap_correction)
        self.cb_temporal_filtering = QtGui.QCheckBox(self.tab_general)
        self.cb_temporal_filtering.setObjectName("cb_temporal_filtering")
        self.verticalLayout_2.addWidget(self.cb_temporal_filtering)
        self.cb_movement_correction = QtGui.QCheckBox(self.tab_general)
        self.cb_movement_correction.setObjectName("cb_movement_correction")
        self.verticalLayout_2.addWidget(self.cb_movement_correction)
        self.cb_slicetime_correction = QtGui.QCheckBox(self.tab_general)
        self.cb_slicetime_correction.setObjectName("cb_slicetime_correction")
        self.verticalLayout_2.addWidget(self.cb_slicetime_correction)
        self.cb_atlas_registration = QtGui.QCheckBox(self.tab_general)
        self.cb_atlas_registration.setObjectName("cb_atlas_registration")
        self.verticalLayout_2.addWidget(self.cb_atlas_registration)
        self.cb_show_registration_results = QtGui.QCheckBox(self.tab_general)
        self.cb_show_registration_results.setEnabled(False)
        self.cb_show_registration_results.setChecked(False)
        self.cb_show_registration_results.setObjectName("cb_show_registration_results")
        self.verticalLayout_2.addWidget(self.cb_show_registration_results)
        self.cb_spatial_filtering = QtGui.QCheckBox(self.tab_general)
        self.cb_spatial_filtering.setObjectName("cb_spatial_filtering")
        self.verticalLayout_2.addWidget(self.cb_spatial_filtering)
        self.cb_create_mask = QtGui.QCheckBox(self.tab_general)
        self.cb_create_mask.setObjectName("cb_create_mask")
        self.verticalLayout_2.addWidget(self.cb_create_mask)
        self.cb_show_mask = QtGui.QCheckBox(self.tab_general)
        self.cb_show_mask.setEnabled(False)
        self.cb_show_mask.setObjectName("cb_show_mask")
        self.verticalLayout_2.addWidget(self.cb_show_mask)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.cb_set_repetition = QtGui.QCheckBox(self.tab_general)
        self.cb_set_repetition.setEnabled(True)
        self.cb_set_repetition.setAutoFillBackground(False)
        self.cb_set_repetition.setChecked(True)
        self.cb_set_repetition.setTristate(False)
        self.cb_set_repetition.setObjectName("cb_set_repetition")
        self.horizontalLayout_11.addWidget(self.cb_set_repetition)
        self.dsb_repetition_time = QtGui.QDoubleSpinBox(self.tab_general)
        self.dsb_repetition_time.setMaximum(600.0)
        self.dsb_repetition_time.setObjectName("dsb_repetition_time")
        self.horizontalLayout_11.addWidget(self.dsb_repetition_time)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        spacerItem = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem)
        self.l_output = QtGui.QLabel(self.tab_general)
        self.l_output.setMinimumSize(QtCore.QSize(0, 16))
        self.l_output.setMaximumSize(QtCore.QSize(16777215, 16))
        self.l_output.setObjectName("l_output")
        self.verticalLayout_7.addWidget(self.l_output)
        self.l_directory = QtGui.QLabel(self.tab_general)
        self.l_directory.setMinimumSize(QtCore.QSize(0, 16))
        self.l_directory.setMaximumSize(QtCore.QSize(16777215, 16))
        self.l_directory.setObjectName("l_directory")
        self.verticalLayout_7.addWidget(self.l_directory)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.le_directory = QtGui.QLineEdit(self.tab_general)
        self.le_directory.setMaximumSize(QtCore.QSize(16777215, 27))
        self.le_directory.setObjectName("le_directory")
        self.horizontalLayout_12.addWidget(self.le_directory)
        self.b_output_directory = QtGui.QPushButton(self.tab_general)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_output_directory.sizePolicy().hasHeightForWidth())
        self.b_output_directory.setSizePolicy(sizePolicy)
        self.b_output_directory.setMinimumSize(QtCore.QSize(50, 27))
        self.b_output_directory.setMaximumSize(QtCore.QSize(50, 27))
        self.b_output_directory.setObjectName("b_output_directory")
        self.horizontalLayout_12.addWidget(self.b_output_directory)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.l_prefix = QtGui.QLabel(self.tab_general)
        self.l_prefix.setMaximumSize(QtCore.QSize(16777215, 16))
        self.l_prefix.setObjectName("l_prefix")
        self.verticalLayout_7.addWidget(self.l_prefix)
        self.le_prefix = QtGui.QLineEdit(self.tab_general)
        self.le_prefix.setMaximumSize(QtCore.QSize(16777215, 27))
        self.le_prefix.setObjectName("le_prefix")
        self.verticalLayout_7.addWidget(self.le_prefix)
        spacerItem1 = QtGui.QSpacerItem(20, 39, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_13.addLayout(self.verticalLayout_7)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.l_temporal_filtering = QtGui.QLabel(self.tab_general)
        self.l_temporal_filtering.setObjectName("l_temporal_filtering")
        self.verticalLayout_4.addWidget(self.l_temporal_filtering)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cb_high_pass = QtGui.QCheckBox(self.tab_general)
        self.cb_high_pass.setEnabled(True)
        self.cb_high_pass.setAutoFillBackground(False)
        self.cb_high_pass.setChecked(True)
        self.cb_high_pass.setTristate(False)
        self.cb_high_pass.setObjectName("cb_high_pass")
        self.horizontalLayout_8.addWidget(self.cb_high_pass)
        self.cb_low_pass = QtGui.QCheckBox(self.tab_general)
        self.cb_low_pass.setObjectName("cb_low_pass")
        self.horizontalLayout_8.addWidget(self.cb_low_pass)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.l_cutoff_high_pass = QtGui.QLabel(self.tab_general)
        self.l_cutoff_high_pass.setObjectName("l_cutoff_high_pass")
        self.horizontalLayout_7.addWidget(self.l_cutoff_high_pass)
        self.sb_hp_cutoff = QtGui.QSpinBox(self.tab_general)
        self.sb_hp_cutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_hp_cutoff.setMaximum(600)
        self.sb_hp_cutoff.setProperty("value", 90)
        self.sb_hp_cutoff.setObjectName("sb_hp_cutoff")
        self.horizontalLayout_7.addWidget(self.sb_hp_cutoff)
        self.l_cutoff_hp_s = QtGui.QLabel(self.tab_general)
        self.l_cutoff_hp_s.setObjectName("l_cutoff_hp_s")
        self.horizontalLayout_7.addWidget(self.l_cutoff_hp_s)
        self.l_cutoff_low_pass = QtGui.QLabel(self.tab_general)
        self.l_cutoff_low_pass.setObjectName("l_cutoff_low_pass")
        self.horizontalLayout_7.addWidget(self.l_cutoff_low_pass)
        self.sb_lp_cutoff = QtGui.QSpinBox(self.tab_general)
        self.sb_lp_cutoff.setEnabled(False)
        self.sb_lp_cutoff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_lp_cutoff.setMaximum(600)
        self.sb_lp_cutoff.setProperty("value", 3)
        self.sb_lp_cutoff.setObjectName("sb_lp_cutoff")
        self.horizontalLayout_7.addWidget(self.sb_lp_cutoff)
        self.l_cutoff_lp_s = QtGui.QLabel(self.tab_general)
        self.l_cutoff_lp_s.setObjectName("l_cutoff_lp_s")
        self.horizontalLayout_7.addWidget(self.l_cutoff_lp_s)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.l_spatial_filtering = QtGui.QLabel(self.tab_general)
        self.l_spatial_filtering.setObjectName("l_spatial_filtering")
        self.horizontalLayout_9.addWidget(self.l_spatial_filtering)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.l_miscellaneous = QtGui.QLabel(self.tab_general)
        self.l_miscellaneous.setObjectName("l_miscellaneous")
        self.horizontalLayout_9.addWidget(self.l_miscellaneous)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.l_fwhm = QtGui.QLabel(self.tab_general)
        self.l_fwhm.setObjectName("l_fwhm")
        self.horizontalLayout_10.addWidget(self.l_fwhm)
        self.sb_fwhm = QtGui.QSpinBox(self.tab_general)
        self.sb_fwhm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_fwhm.setMaximum(600)
        self.sb_fwhm.setProperty("value", 6)
        self.sb_fwhm.setObjectName("sb_fwhm")
        self.horizontalLayout_10.addWidget(self.sb_fwhm)
        self.l_spatial_filtering_mm = QtGui.QLabel(self.tab_general)
        self.l_spatial_filtering_mm.setObjectName("l_spatial_filtering_mm")
        self.horizontalLayout_10.addWidget(self.l_spatial_filtering_mm)
        spacerItem4 = QtGui.QSpacerItem(38, 49, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cb_debug_output = QtGui.QCheckBox(self.tab_general)
        self.cb_debug_output.setObjectName("cb_debug_output")
        self.verticalLayout_6.addWidget(self.cb_debug_output)
        self.cb_write_logfile = QtGui.QCheckBox(self.tab_general)
        self.cb_write_logfile.setObjectName("cb_write_logfile")
        self.verticalLayout_6.addWidget(self.cb_write_logfile)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.l_mask_options = QtGui.QLabel(self.tab_general)
        self.l_mask_options.setObjectName("l_mask_options")
        self.verticalLayout_4.addWidget(self.l_mask_options)
        self.rb_create_average_mask = QtGui.QRadioButton(self.tab_general)
        self.rb_create_average_mask.setChecked(True)
        self.rb_create_average_mask.setObjectName("rb_create_average_mask")
        self.verticalLayout_4.addWidget(self.rb_create_average_mask)
        self.rb_create_mask_subject = QtGui.QRadioButton(self.tab_general)
        self.rb_create_mask_subject.setObjectName("rb_create_mask_subject")
        self.verticalLayout_4.addWidget(self.rb_create_mask_subject)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.l_maximum_number_of_voxel = QtGui.QLabel(self.tab_general)
        self.l_maximum_number_of_voxel.setObjectName("l_maximum_number_of_voxel")
        self.horizontalLayout_6.addWidget(self.l_maximum_number_of_voxel)
        self.sb_max_num_voxel = QtGui.QSpinBox(self.tab_general)
        self.sb_max_num_voxel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sb_max_num_voxel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_max_num_voxel.setMaximum(1000000000)
        self.sb_max_num_voxel.setProperty("value", 50000)
        self.sb_max_num_voxel.setObjectName("sb_max_num_voxel")
        self.horizontalLayout_6.addWidget(self.sb_max_num_voxel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.tabWidget.addTab(self.tab_general, "")
        self.tab_reg_settings = QtGui.QWidget()
        self.tab_reg_settings.setObjectName("tab_reg_settings")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_reg_settings)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.l_atlas_registration = QtGui.QLabel(self.tab_reg_settings)
        self.l_atlas_registration.setObjectName("l_atlas_registration")
        self.verticalLayout_8.addWidget(self.l_atlas_registration)
        self.l_template = QtGui.QLabel(self.tab_reg_settings)
        self.l_template.setObjectName("l_template")
        self.verticalLayout_8.addWidget(self.l_template)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.comboBox_template = QtGui.QComboBox(self.tab_reg_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_template.sizePolicy().hasHeightForWidth())
        self.comboBox_template.setSizePolicy(sizePolicy)
        self.comboBox_template.setMinimumSize(QtCore.QSize(191, 27))
        self.comboBox_template.setMaximumSize(QtCore.QSize(191, 27))
        self.comboBox_template.setObjectName("comboBox_template")
        self.horizontalLayout_15.addWidget(self.comboBox_template)
        self.b_view = QtGui.QPushButton(self.tab_reg_settings)
        self.b_view.setMinimumSize(QtCore.QSize(61, 0))
        self.b_view.setMaximumSize(QtCore.QSize(61, 16777215))
        self.b_view.setObjectName("b_view")
        self.horizontalLayout_15.addWidget(self.b_view)
        spacerItem5 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.l_functional_anatomical_image = QtGui.QLabel(self.tab_reg_settings)
        self.l_functional_anatomical_image.setObjectName("l_functional_anatomical_image")
        self.verticalLayout_8.addWidget(self.l_functional_anatomical_image)
        self.lw_functional_anatomical_image = QtGui.QListWidget(self.tab_reg_settings)
        self.lw_functional_anatomical_image.setObjectName("lw_functional_anatomical_image")
        self.verticalLayout_8.addWidget(self.lw_functional_anatomical_image)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.b_add_anatomical_image = QtGui.QPushButton(self.tab_reg_settings)
        self.b_add_anatomical_image.setObjectName("b_add_anatomical_image")
        self.horizontalLayout_16.addWidget(self.b_add_anatomical_image)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.b_remove_anatomical_image = QtGui.QPushButton(self.tab_reg_settings)
        self.b_remove_anatomical_image.setObjectName("b_remove_anatomical_image")
        self.horizontalLayout_16.addWidget(self.b_remove_anatomical_image)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.l_registration_pipeline = QtGui.QLabel(self.tab_reg_settings)
        self.l_registration_pipeline.setObjectName("l_registration_pipeline")
        self.verticalLayout_8.addWidget(self.l_registration_pipeline)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.fr_reg_pipe_1 = QtGui.QFrame(self.tab_reg_settings)
        self.fr_reg_pipe_1.setMinimumSize(QtCore.QSize(131, 131))
        self.fr_reg_pipe_1.setMaximumSize(QtCore.QSize(161, 16777215))
        self.fr_reg_pipe_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_reg_pipe_1.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_reg_pipe_1.setObjectName("fr_reg_pipe_1")
        self.cb_rigid_registration = QtGui.QCheckBox(self.fr_reg_pipe_1)
        self.cb_rigid_registration.setGeometry(QtCore.QRect(10, 10, 141, 22))
        self.cb_rigid_registration.setObjectName("cb_rigid_registration")
        self.l_max_iterations_p1 = QtGui.QLabel(self.fr_reg_pipe_1)
        self.l_max_iterations_p1.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.l_max_iterations_p1.setObjectName("l_max_iterations_p1")
        self.sb_max_iterations_p1 = QtGui.QSpinBox(self.fr_reg_pipe_1)
        self.sb_max_iterations_p1.setEnabled(False)
        self.sb_max_iterations_p1.setGeometry(QtCore.QRect(10, 50, 141, 21))
        self.sb_max_iterations_p1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_max_iterations_p1.setMaximum(1000)
        self.sb_max_iterations_p1.setProperty("value", 500)
        self.sb_max_iterations_p1.setObjectName("sb_max_iterations_p1")
        self.cb_prealign_images = QtGui.QCheckBox(self.fr_reg_pipe_1)
        self.cb_prealign_images.setEnabled(False)
        self.cb_prealign_images.setGeometry(QtCore.QRect(10, 80, 141, 22))
        self.cb_prealign_images.setObjectName("cb_prealign_images")
        self.horizontalLayout_19.addWidget(self.fr_reg_pipe_1)
        self.l_next1 = QtGui.QLabel(self.tab_reg_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_next1.sizePolicy().hasHeightForWidth())
        self.l_next1.setSizePolicy(sizePolicy)
        self.l_next1.setMinimumSize(QtCore.QSize(0, 0))
        self.l_next1.setObjectName("l_next1")
        self.horizontalLayout_19.addWidget(self.l_next1)
        self.fr_reg_pipe_2 = QtGui.QFrame(self.tab_reg_settings)
        self.fr_reg_pipe_2.setMinimumSize(QtCore.QSize(161, 131))
        self.fr_reg_pipe_2.setMaximumSize(QtCore.QSize(161, 16777215))
        self.fr_reg_pipe_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_reg_pipe_2.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_reg_pipe_2.setObjectName("fr_reg_pipe_2")
        self.cb_affine_registration = QtGui.QCheckBox(self.fr_reg_pipe_2)
        self.cb_affine_registration.setGeometry(QtCore.QRect(10, 10, 141, 22))
        self.cb_affine_registration.setObjectName("cb_affine_registration")
        self.l_max_iterations_p2 = QtGui.QLabel(self.fr_reg_pipe_2)
        self.l_max_iterations_p2.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.l_max_iterations_p2.setObjectName("l_max_iterations_p2")
        self.sb_max_iterations_p2 = QtGui.QSpinBox(self.fr_reg_pipe_2)
        self.sb_max_iterations_p2.setEnabled(False)
        self.sb_max_iterations_p2.setGeometry(QtCore.QRect(10, 50, 141, 21))
        self.sb_max_iterations_p2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_max_iterations_p2.setMaximum(1000)
        self.sb_max_iterations_p2.setProperty("value", 20)
        self.sb_max_iterations_p2.setObjectName("sb_max_iterations_p2")
        self.horizontalLayout_19.addWidget(self.fr_reg_pipe_2)
        self.l_next2 = QtGui.QLabel(self.tab_reg_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_next2.sizePolicy().hasHeightForWidth())
        self.l_next2.setSizePolicy(sizePolicy)
        self.l_next2.setObjectName("l_next2")
        self.horizontalLayout_19.addWidget(self.l_next2)
        self.fr_reg_pipe_3 = QtGui.QFrame(self.tab_reg_settings)
        self.fr_reg_pipe_3.setMinimumSize(QtCore.QSize(191, 131))
        self.fr_reg_pipe_3.setMaximumSize(QtCore.QSize(191, 16777215))
        self.fr_reg_pipe_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fr_reg_pipe_3.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_reg_pipe_3.setObjectName("fr_reg_pipe_3")
        self.cb_deformable_registration = QtGui.QCheckBox(self.fr_reg_pipe_3)
        self.cb_deformable_registration.setGeometry(QtCore.QRect(10, 10, 181, 22))
        self.cb_deformable_registration.setObjectName("cb_deformable_registration")
        self.l_max_iterations_p3 = QtGui.QLabel(self.fr_reg_pipe_3)
        self.l_max_iterations_p3.setGeometry(QtCore.QRect(10, 31, 141, 20))
        self.l_max_iterations_p3.setObjectName("l_max_iterations_p3")
        self.sb_max_iterations_p3 = QtGui.QSpinBox(self.fr_reg_pipe_3)
        self.sb_max_iterations_p3.setEnabled(False)
        self.sb_max_iterations_p3.setGeometry(QtCore.QRect(10, 51, 141, 20))
        self.sb_max_iterations_p3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_max_iterations_p3.setMaximum(1000)
        self.sb_max_iterations_p3.setProperty("value", 20)
        self.sb_max_iterations_p3.setObjectName("sb_max_iterations_p3")
        self.sb_max_deformation = QtGui.QSpinBox(self.fr_reg_pipe_3)
        self.sb_max_deformation.setEnabled(False)
        self.sb_max_deformation.setGeometry(QtCore.QRect(10, 100, 141, 21))
        self.sb_max_deformation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_max_deformation.setMaximum(1000)
        self.sb_max_deformation.setProperty("value", 10)
        self.sb_max_deformation.setObjectName("sb_max_deformation")
        self.l_max_deformation = QtGui.QLabel(self.fr_reg_pipe_3)
        self.l_max_deformation.setGeometry(QtCore.QRect(10, 80, 161, 16))
        self.l_max_deformation.setObjectName("l_max_deformation")
        self.l_max_deformation_mm = QtGui.QLabel(self.fr_reg_pipe_3)
        self.l_max_deformation_mm.setGeometry(QtCore.QRect(160, 100, 31, 21))
        self.l_max_deformation_mm.setObjectName("l_max_deformation_mm")
        self.horizontalLayout_19.addWidget(self.fr_reg_pipe_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.l_interpolator_function = QtGui.QLabel(self.tab_reg_settings)
        self.l_interpolator_function.setObjectName("l_interpolator_function")
        self.horizontalLayout_17.addWidget(self.l_interpolator_function)
        self.comboBox_interpol_func = QtGui.QComboBox(self.tab_reg_settings)
        self.comboBox_interpol_func.setMinimumSize(QtCore.QSize(191, 21))
        self.comboBox_interpol_func.setObjectName("comboBox_interpol_func")
        self.horizontalLayout_17.addWidget(self.comboBox_interpol_func)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.l_output_resolution = QtGui.QLabel(self.tab_reg_settings)
        self.l_output_resolution.setObjectName("l_output_resolution")
        self.horizontalLayout_17.addWidget(self.l_output_resolution)
        self.le_output_resolution = QtGui.QLineEdit(self.tab_reg_settings)
        self.le_output_resolution.setAlignment(QtCore.Qt.AlignCenter)
        self.le_output_resolution.setObjectName("le_output_resolution")
        self.horizontalLayout_17.addWidget(self.le_output_resolution)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.tabWidget.addTab(self.tab_reg_settings, "")
        self.tab_help = QtGui.QWidget()
        self.tab_help.setObjectName("tab_help")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_help)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.comboBox_help = QtGui.QComboBox(self.tab_help)
        self.comboBox_help.setObjectName("comboBox_help")
        self.verticalLayout_11.addWidget(self.comboBox_help)
        self.web_help = QtWebKit.QWebView(self.tab_help)
        self.web_help.setUrl(QtCore.QUrl("about:blank"))
        self.web_help.setObjectName("web_help")
        self.verticalLayout_11.addWidget(self.web_help)
        self.tabWidget.addTab(self.tab_help, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b_start_proc = QtGui.QPushButton(Fenster)
        self.b_start_proc.setObjectName("b_start_proc")
        self.horizontalLayout_2.addWidget(self.b_start_proc)
        self.b_save_settings = QtGui.QPushButton(Fenster)
        self.b_save_settings.setObjectName("b_save_settings")
        self.horizontalLayout_2.addWidget(self.b_save_settings)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b_exit = QtGui.QPushButton(Fenster)
        self.b_exit.setObjectName("b_exit")
        self.horizontalLayout_3.addWidget(self.b_exit)
        self.b_load_settings = QtGui.QPushButton(Fenster)
        self.b_load_settings.setObjectName("b_load_settings")
        self.horizontalLayout_3.addWidget(self.b_load_settings)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.progressBar = QtGui.QProgressBar(Fenster)
        self.progressBar.setProperty("value", 1)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(Fenster)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Fenster)

    def retranslateUi(self, Fenster):
        Fenster.setWindowTitle(QtGui.QApplication.translate("Fenster", "Lipsia Preprocessing", None, QtGui.QApplication.UnicodeUTF8))
        self.l_input_files.setText(QtGui.QApplication.translate("Fenster", "Input fIles:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_image_file.setText(QtGui.QApplication.translate("Fenster", "Add images", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_image_directory.setText(QtGui.QApplication.translate("Fenster", "Add dicom dir", None, QtGui.QApplication.UnicodeUTF8))
        self.b_remove_file.setText(QtGui.QApplication.translate("Fenster", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.l_preprocessing_steps.setText(QtGui.QApplication.translate("Fenster", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Preprocessing steps</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fieldmap_correction.setText(QtGui.QApplication.translate("Fenster", "Fieldmap correction", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_temporal_filtering.setText(QtGui.QApplication.translate("Fenster", "Temporal filtering", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_movement_correction.setText(QtGui.QApplication.translate("Fenster", "Movement correction", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_slicetime_correction.setText(QtGui.QApplication.translate("Fenster", "Slicetime correction", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_atlas_registration.setText(QtGui.QApplication.translate("Fenster", "Atlas registration", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_show_registration_results.setText(QtGui.QApplication.translate("Fenster", "Show registration results (interruption)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_spatial_filtering.setText(QtGui.QApplication.translate("Fenster", "Spatial filtering", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_create_mask.setText(QtGui.QApplication.translate("Fenster", "Create a mask", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_show_mask.setText(QtGui.QApplication.translate("Fenster", "Show mask (interruption)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_set_repetition.setText(QtGui.QApplication.translate("Fenster", "Set repetition time:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_output.setText(QtGui.QApplication.translate("Fenster", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Output</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.l_directory.setText(QtGui.QApplication.translate("Fenster", "Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.le_directory.setText(QtGui.QApplication.translate("Fenster", "/home/blah/blah", None, QtGui.QApplication.UnicodeUTF8))
        self.b_output_directory.setText(QtGui.QApplication.translate("Fenster", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.l_prefix.setText(QtGui.QApplication.translate("Fenster", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.le_prefix.setText(QtGui.QApplication.translate("Fenster", "preproc_", None, QtGui.QApplication.UnicodeUTF8))
        self.l_temporal_filtering.setText(QtGui.QApplication.translate("Fenster", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Temporal filtering</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_high_pass.setText(QtGui.QApplication.translate("Fenster", "High pass filter", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_low_pass.setText(QtGui.QApplication.translate("Fenster", "Low pass", None, QtGui.QApplication.UnicodeUTF8))
        self.l_cutoff_high_pass.setText(QtGui.QApplication.translate("Fenster", "Cutoff:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_cutoff_hp_s.setText(QtGui.QApplication.translate("Fenster", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.l_cutoff_low_pass.setText(QtGui.QApplication.translate("Fenster", "Cutoff:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_cutoff_lp_s.setText(QtGui.QApplication.translate("Fenster", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.l_spatial_filtering.setText(QtGui.QApplication.translate("Fenster", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Spatial filtering</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.l_miscellaneous.setText(QtGui.QApplication.translate("Fenster", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Miscellaneous</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.l_fwhm.setText(QtGui.QApplication.translate("Fenster", "FWHM:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_spatial_filtering_mm.setText(QtGui.QApplication.translate("Fenster", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_debug_output.setText(QtGui.QApplication.translate("Fenster", "Debug Output", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_write_logfile.setText(QtGui.QApplication.translate("Fenster", "Write logfile", None, QtGui.QApplication.UnicodeUTF8))
        self.l_mask_options.setText(QtGui.QApplication.translate("Fenster", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Mask options</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_create_average_mask.setText(QtGui.QApplication.translate("Fenster", "Create an average mask", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_create_mask_subject.setText(QtGui.QApplication.translate("Fenster", "Create a mask for every subject", None, QtGui.QApplication.UnicodeUTF8))
        self.l_maximum_number_of_voxel.setText(QtGui.QApplication.translate("Fenster", "Maximum number of voxel:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_general), QtGui.QApplication.translate("Fenster", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.l_atlas_registration.setText(QtGui.QApplication.translate("Fenster", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Atlas registration</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.l_template.setText(QtGui.QApplication.translate("Fenster", "Template:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_view.setText(QtGui.QApplication.translate("Fenster", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.l_functional_anatomical_image.setText(QtGui.QApplication.translate("Fenster", "Functional image -> Anatomical image", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add_anatomical_image.setText(QtGui.QApplication.translate("Fenster", "Add anatomical image", None, QtGui.QApplication.UnicodeUTF8))
        self.b_remove_anatomical_image.setText(QtGui.QApplication.translate("Fenster", "Remove anatomical image", None, QtGui.QApplication.UnicodeUTF8))
        self.l_registration_pipeline.setText(QtGui.QApplication.translate("Fenster", "Registration pipeline:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_rigid_registration.setText(QtGui.QApplication.translate("Fenster", "Rigid Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.l_max_iterations_p1.setText(QtGui.QApplication.translate("Fenster", "Maximum iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_prealign_images.setText(QtGui.QApplication.translate("Fenster", "Prealign images", None, QtGui.QApplication.UnicodeUTF8))
        self.l_next1.setText(QtGui.QApplication.translate("Fenster", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">&gt;</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_affine_registration.setText(QtGui.QApplication.translate("Fenster", "Affine Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.l_max_iterations_p2.setText(QtGui.QApplication.translate("Fenster", "Maximum iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_next2.setText(QtGui.QApplication.translate("Fenster", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">&gt;</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_deformable_registration.setText(QtGui.QApplication.translate("Fenster", "Deformable registration", None, QtGui.QApplication.UnicodeUTF8))
        self.l_max_iterations_p3.setText(QtGui.QApplication.translate("Fenster", "Maximum iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_max_deformation.setText(QtGui.QApplication.translate("Fenster", "Maximum deformation:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_max_deformation_mm.setText(QtGui.QApplication.translate("Fenster", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.l_interpolator_function.setText(QtGui.QApplication.translate("Fenster", "Interpolator function:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_output_resolution.setText(QtGui.QApplication.translate("Fenster", "Output resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.le_output_resolution.setText(QtGui.QApplication.translate("Fenster", "3,3,3", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_reg_settings), QtGui.QApplication.translate("Fenster", "Registration Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_help), QtGui.QApplication.translate("Fenster", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.b_start_proc.setText(QtGui.QApplication.translate("Fenster", "Start preprocessing", None, QtGui.QApplication.UnicodeUTF8))
        self.b_save_settings.setText(QtGui.QApplication.translate("Fenster", "Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.b_exit.setText(QtGui.QApplication.translate("Fenster", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.b_load_settings.setText(QtGui.QApplication.translate("Fenster", "Load  Settings", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
