# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/Preprocessing_Layouted.ui'
#
# Created: Tue Apr 24 11:21:14 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(642, 628)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.imageList = QtGui.QListView(self.groupBox)
        self.imageList.setObjectName(_fromUtf8("imageList"))
        self.horizontalLayout.addWidget(self.imageList)
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.b_addImages = QtGui.QPushButton(self.frame_2)
        self.b_addImages.setObjectName(_fromUtf8("b_addImages"))
        self.verticalLayout_2.addWidget(self.b_addImages)
        self.b_addDirs = QtGui.QPushButton(self.frame_2)
        self.b_addDirs.setObjectName(_fromUtf8("b_addDirs"))
        self.verticalLayout_2.addWidget(self.b_addDirs)
        self.b_removeListEntry = QtGui.QPushButton(self.frame_2)
        self.b_removeListEntry.setObjectName(_fromUtf8("b_removeListEntry"))
        self.verticalLayout_2.addWidget(self.b_removeListEntry)
        self.b_clearImageList = QtGui.QPushButton(self.frame_2)
        self.b_clearImageList.setObjectName(_fromUtf8("b_clearImageList"))
        self.verticalLayout_2.addWidget(self.b_clearImageList)
        self.verticalLayout_3.addWidget(self.frame_2)
        spacerItem = QtGui.QSpacerItem(20, 319, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Save_Script = QtGui.QAction(MainWindow)
        self.action_Save_Script.setObjectName(_fromUtf8("action_Save_Script"))
        self.actionSave_script_as = QtGui.QAction(MainWindow)
        self.actionSave_script_as.setObjectName(_fromUtf8("actionSave_script_as"))
        self.action_Open_script = QtGui.QAction(MainWindow)
        self.action_Open_script.setObjectName(_fromUtf8("action_Open_script"))
        self.action_Exit = QtGui.QAction(MainWindow)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.menu_File.addAction(self.action_Open_script)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Save_Script)
        self.menu_File.addAction(self.actionSave_script_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lipsia Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Images to process", None, QtGui.QApplication.UnicodeUTF8))
        self.b_addImages.setText(QtGui.QApplication.translate("MainWindow", "Add image(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.b_addDirs.setText(QtGui.QApplication.translate("MainWindow", "Add dir(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.b_removeListEntry.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.b_clearImageList.setText(QtGui.QApplication.translate("MainWindow", "Clear list", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_Script.setText(QtGui.QApplication.translate("MainWindow", "&Save script", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_script_as.setText(QtGui.QApplication.translate("MainWindow", "Save script &as...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open_script.setText(QtGui.QApplication.translate("MainWindow", "&Open script...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))

